variables:
  DOCKER_DRIVER: overlay2
  PACKAGES_LIST: ros2trace tracetools tracetools_launch tracetools_read tracetools_test tracetools_trace
  base_image_id: registry.gitlab.com/ros-tracing/ci_base
  distro: eloquent

.global_artifacts: &global_artifacts
  artifacts:
    paths:
      - install
      - build/*/test_results/*/*.xunit.xml
      - build/*/pytest.xml
    reports:
      junit:
        - build/*/test_results/*/*.xunit.xml
        - build/*/pytest.xml

before_script:
  - vcs import < instrumented.repos
  - . /root/ws/install/local_setup.sh

tracing_enabled:
  image: $base_image_id:$distro
  script:
    - lttng --version && apt list lttng-tools liblttng-ust-dev python3-lttng python3-babeltrace
    - lttng-sessiond --daemonize
    - colcon build --symlink-install --event-handlers console_cohesion+ --packages-up-to $PACKAGES_LIST
    - . install/setup.sh
    - ./build/tracetools/status
    - colcon test --event-handlers console_cohesion+ --packages-select $PACKAGES_LIST
    - colcon test-result --all --verbose
  <<: *global_artifacts

tracing_disabled:
  image: $base_image_id:$distro
  script:
    - colcon build --symlink-install --event-handlers console_cohesion+ --cmake-args " -DTRACETOOLS_DISABLED=ON" --packages-up-to $PACKAGES_LIST
    - (! ./build/tracetools/status)
    - colcon test --event-handlers console_cohesion+ --packages-select $PACKAGES_LIST
    - colcon test-result --all --verbose
  <<: *global_artifacts

no_lttng:
  image: $base_image_id:$distro-base
  script:
    - colcon build --symlink-install --event-handlers console_cohesion+ --packages-up-to $PACKAGES_LIST
    - (! ./build/tracetools/status)
    - colcon test --event-handlers console_cohesion+ --packages-select $PACKAGES_LIST
    - colcon test-result --all --verbose
  <<: *global_artifacts
