name: Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            build-type: binary
          - os: ubuntu-20.04
            build-type: source
          - os: macos-latest
            build-type: source
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@master
      with:
        required-ros-distributions: ${{ matrix.build-type == 'binary' && 'rolling' || '' }}
    - name: Install LTTng
      run: |
        sudo apt-get update
        sudo apt-get install -q -y lttng-tools liblttng-ust-dev python3-lttng python3-babeltrace python3-pandas
      if: startsWith(matrix.os, 'ubuntu-')
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: ros2trace tracetools tracetools_launch tracetools_read tracetools_test tracetools_trace
        target-ros2-distro: rolling
        vcs-repo-file-url: ${{ matrix.build-type == 'source' && 'https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos' || '' }}
        colcon-defaults: |
          {
            "build": {
              "mixin": [
                  "coverage-gcc",
                  "coverage-pytest"
              ]
            },
            "test": {
              "mixin": [
                "coverage-pytest"
              ]
            }
          }
    - uses: codecov/codecov-action@v1
      with:
        files: ros_ws/lcov/total_coverage.info,ros_ws/coveragepy/.coverage
        name: codecov-umbrella
